# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'sample-apps-ios-xcode7b3-swift' do

end

target 'sample-apps-ios-xcode7b3-swiftTests' do

end

target 'sample-apps-ios-xcode7b3-swiftUITests' do

end

